[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = "0.3"
heapless = "0.7.17"
postcard = "1.0.8"
serde = { version = "1.0", features = ["derive"], default-features = false }

[features]
std = []
